name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build system
        run: |
          pip install --upgrade pip
          pip install build

      - name: Install dependencies and run tests
        run: |
          pip install .
          pip install pytest
          pytest

      - name: Build the package
        run: |
          python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
